management:
  endpoints:
    web:
      exposure:
        include: '*'
        #exclude: beans
         # - beans
          #- mappings
         # - shutdown
  endpoint:
    shutdown:
      enabled: true